profile_name_icon_loc = "//*[@data-click='profile_icon']"
home_btn_loc = "//div[@data-click='home_icon']"

'''Post Locators'''
write_post_txt_loc = "//*[@data-testid='status-attachment-mentions-input']"
share_post_btn_loc = "//*[@data-testid='react-composer-post-button']"
click_write_post_txt_loc = "//div[@id='pagelet_composer']//div[contains(@class,'clearfix')]"
assert_post_loc = "//*[@data-testid='newsFeedStream']//p[contains(text(),'{}')]"
assert_image_loc = "//*[@data-testid = 'newsFeedStream']//*[contains(@class,'userContentWrapper')]//a[contains(@data-ploi,'.jpg')]"
upload_image_loc = "(//input[@name='composer_photo[]' and contains(@accept, 'video')])[1]"
assert_video_loc = "//div[@data-testid='newsFeedStream']//div[contains(text(),'The video in your post')]"
notifications_count_loc = "notificationsCountValue"
post_options_loc = "(//*[@data-testid='post_chevron_button'])[{}]"
add_emoji_icon_loc = "//*[@aria-label='Insert an emoji']"
smiley_img_loc = "(//*[text()='Smileys & people']/following-sibling::div//img)[1]"
edit_post_link_loc = "//span[text()='Edit post']"
delete_post_link_loc = "//span[text()='Delete']"
save_edited_post_btn_loc = "//*[@name='save' and @type='submit']"
remove_photo_icon_loc = "//*[@title='Remove Photo']"
all_post_options_loc = "//a[@data-testid='post_chevron_button']"
delete_post_confirm_btn_loc = "//*[contains(@class,'layerConfirm uiOverlayButton') and @type='submit']"

''''Profile locators'''
posted_by_you_lbl_loc = "//*[@id='timeline_overview']//*[text() = 'You']"
manage_posts_btn_loc = "//*[@id='profile_timeline_overview_switcher_pagelet']//*[text() = 'Manage posts']"
manage_posts_grid_view_btn_loc = "//*[@id='profile_timeline_overview_switcher_pagelet']//*[text() = 'Grid view']"
manage_posts_list_view_btn_loc = "//*[@id='profile_timeline_overview_switcher_pagelet']//*[text() = 'List view']"
no_posts_empty_state_loc = "//*[@id='timeline_overview']//*[text() = 'No posts']"

''''Messenger Locators'''
messenger_icon_loc = "//*[@name='mercurymessages']/div"
new_message_link_loc = "//*[text() = 'New Message']"
to_list_txt_loc = "//*[contains(@id,'add-friends')]//following-sibling::div"
to_list_input_loc = "//*[contains(@id,'add-friends')]//following-sibling::div//input[@type='text']"
select_recepient_option_loc = "//*[@class='compact']//li[1]"
message_area_txt_loc = "//div[@role='combobox']"
read_message_txt_loc = "(//*[text() = '{}'])[2]"
select_message_content_loc = "//*[@class = 'messagesContent']"

''''Page Locators'''
pages_link_loc = "//*[@data-testid = 'left_nav_item_Pages' and @title = 'Pages']"
create_page_link_loc = "//*[text()='Create Page']//ancestor::a[contains(@href,'page')]"
business_page_button_loc = "//*[@data-testid='BUSINESS_SUPERCATEGORYCardContainer']//*[text()='Get Started’]"
community_page_button_loc = "//*[@data-testid='NON_BUSINESS_SUPERCATEGORYCardContainer']//*[text()='Get Started’]"
page_name_loc = "//input[@data-testid='NON_BUSINESS_SUPERCATEGORYNameInput']"
category_name_loc = "//span[@data-testid='NON_BUSINESS_SUPERCATEGORYCategoryTypeahead']//input"
continue_page_creation_button_loc = "//div[@data-testid='NON_BUSINESS_SUPERCATEGORYFormContainer']//button[@type='button']"
upload_page_loc = "//input[@name='admin_to_do_profile_pic']"
upload_cover_photo_loc = "//input[@name='admin_to_do_cover_photo']"
wrong_cover_photo_loc = "//*[text()='Please choose an image that's at least 400 pixels wide and at least 150 pixels tall.']"
write_a_post_loc = "//*[@data-testid='react-composer-root']//*[@data-testid='status-attachment-mentions-input']"
publish_post_loc = "//*[@data-testid='react-composer-post-button']"
comment_button_loc = "(//*[@data-testid='fb-ufi-commentlink'])[1]"
comment_input_loc = "(//*[@data-testid='ufi_comment_composer'])[1]"
get_comment_loc = "//*[@class='UFICommentActorAndBodySpacing']//span[@class='UFICommentBody']/span"
read_page_name_txt_loc = "//*[@id='seo_h1_tag']//span"
read_page_post_txt_loc = "//div[contains(@class,'userContentWrapper')]//p"
page_settings_link_loc = "//*[text()='Settings' and @data-hover='tooltip']"
remove_page_link_loc = "//li[@data-testid='settings_section_remove_page']//*[contains(@data-onclick,'SettingsController')]"
permanently_delete_page_link_loc = "//*[text()='Permanently delete {}']"
confirm_delete_page_loc = "//input[@type='button' and @name='confirm']"
page_deleted_popup_msg_loc = "//*[@class = 'pop_content']//*[text()='Page deleted.']"